/*
 * PRODUTOS — versão com descrições reescritas para compliance ANVISA
 * (auxilia/contribui, nunca trata/cura/previne, nenhuma menção a doença grave
 * como alvo do produto — câncer, HIV, leucemia, doenças venéreas, etc.)
 *
 * IMPORTANTE — isso é uma passada de linguagem, não uma certificação regulatória.
 * Removi as violações mais claras e os riscos mais óbvios (nomes de doença grave,
 * "tratar/tratamento/cura/previne", indicação clínica direta). Antes de publicar,
 * vale uma revisão por quem cuida do registro/rotulagem de vocês — principalmente
 * pros itens que eu sinalizei abaixo com ATENÇÃO.
 *
 * ATENÇÃO 1 — "Antiparasitário Natural": o nome do produto em si é uma alegação
 * farmacológica (antiparasitário é categoria de medicamento). Mantive o nome
 * porque não é meu lugar renomear produto de vocês, mas isso merece decisão sua.
 *
 * ATENÇÃO 2 — "Regeneração Hepática": mesmo problema — "regeneração" é alegação
 * médica forte embutida no próprio nome do produto, não só na descrição.
 *
 * nome / cat / img / doencas / preco: mantidos EXATAMENTE como no catálogo atual.
 * desc / descLonga: reescritos.
 */

const produtos = [
{nome:"Açafrão 30ml", cat:"Extratos", desc:"Extrato fitoterápico de Curcuma longa.", descLonga:"Tradicionalmente utilizado por suas propriedades anti-inflamatórias. Contribui para o conforto articular e cardiovascular. Auxilia no equilíbrio emocional e contribui para a manutenção das funções cognitivas e da memória. Rico em compostos antioxidantes, que ajudam a proteger as células do corpo.", img:"imagens/acafrao.png", doencas:["Anti-inflamatório","Digestão"], preco:"30,00"},
{nome:"Agoniada 30ml", cat:"Extratos", desc:"Extrato fitoterápico de Plumeria lancifolia.", descLonga:"Tradicionalmente utilizada para auxiliar no conforto durante a menopausa e no equilíbrio do ciclo menstrual. Contribui para o bem-estar emocional.", img:"imagens/agoniada.png", doencas:["Estômago","Digestão"], preco:"30,00"},
{nome:"Alcachofra 30ml", cat:"Extratos", desc:"Extrato fitoterápico de Cynara scolymus.", descLonga:"Contribui para a manutenção dos níveis de colesterol e glicose já dentro da normalidade. Auxilia a digestão e apoia as funções do fígado e dos rins. Pode contribuir para o processo de emagrecimento quando associada a hábitos alimentares saudáveis.", img:"imagens/alcachofra.png", doencas:["Fígado","Colesterol"], preco:"30,00"},
{nome:"Alcaçuz 30ml", cat:"Extratos", desc:"Extrato fitoterápico de Glycyrrhiza glabra.", descLonga:"Tradicionalmente utilizada por suas propriedades anti-inflamatórias, auxiliando no conforto respiratório. Contribui para o equilíbrio do sistema imunológico e possui ação antioxidante.", img:"imagens/alcacuz.png", doencas:["Estômago","Garganta"], preco:"30,00"},
{nome:"Antiparasitário Natural 30ml", cat:"Extratos", desc:"Auxilia no equilíbrio contra parasitas internos.\n100% natural, vegano.", descLonga:"Fórmula 100% natural e vegana, tradicionalmente utilizada para auxiliar o equilíbrio do organismo contra parasitas internos, sem ingredientes de origem animal.", img:"imagens/antiparasita.png", doencas:["Intestino"], preco:"150,00"},
{nome:"Artemisia 30ml", cat:"Extratos", desc:"Extrato fitoterápico.", descLonga:"Tradicionalmente utilizada para auxiliar no conforto do ciclo menstrual e no equilíbrio hormonal feminino. Contribui para o bem-estar digestivo e para o relaxamento em momentos de ansiedade.", img:"imagens/artemisia.png", doencas:["Intestino"], preco:"30,00"},
{nome:"Assa-Peixe 30ml", cat:"Extratos", desc:"Extrato fitoterápico.", descLonga:"Tradicionalmente utilizada para auxiliar no conforto respiratório, com ação expectorante e anti-inflamatória. Contribui para o bem-estar do sistema digestivo.", img:"imagens/assa-peixe.png", doencas:["Respiratório"], preco:"33,75"},
{nome:"Bálsamo Labial", cat:"Cuidados", desc:"Hidrata e protege os lábios.", descLonga:"Ingredientes: óleo de semente de uva, óleo de coco, cera de abelha, espirulina e óleo essencial de capim limão. Nutre e ajuda a reduzir a sensação de ressecamento, contribuindo para lábios mais macios e hidratados a cada aplicação.", img:"imagens/balsamo_labial.png", doencas:["Pele"], preco:"15,00"},
{nome:"Bio Creme Restaurador 100g", cat:"Cuidados", desc:"Creme restaurador natural.", descLonga:"Creme para uso tópico, com argila verde, dolomita, carvão vegetal ativado, extrato de açafrão, mel, própolis verde não alcoólico e óleo essencial de menta piperita. Contribui para a sensação de conforto em picadas de insetos e para o cuidado da pele em geral. Modo de uso: aplicar antes de dormir diretamente na região desejada, cobrir com papel toalha, envolver com uma faixa e lavar pela manhã.", img:"imagens/biocreme.png", doencas:["Pele"], preco:"36,00"},
{nome:"Boa Noite Plus 30ml", cat:"Extratos", desc:"Extrato fitoterápico.", descLonga:"Composto de Valeriana, Mulungu e Passiflora, tradicionalmente utilizado por sua ação calmante e relaxante. Auxilia no conforto em momentos de tensão e contribui para uma rotina de sono mais tranquila.", img:"imagens/boa_noite_plus.png", doencas:["Sono","Ansiedade"], preco:"35,00"},
{nome:"Cana do Brejo 30ml", cat:"Extratos", desc:"Extrato fitoterápico.", descLonga:"Tradicionalmente utilizada por sua ação diurética, auxiliando o funcionamento renal e o conforto urinário. Contribui para o bem-estar do sistema urinário e possui propriedades anti-inflamatórias.", img:"imagens/cana_do_brejo.png", doencas:["Rins","Bexiga"], preco:"30,00"},
{nome:"Canela de Velho 30ml", cat:"Extratos", desc:"Extrato fitoterápico.", descLonga:"Possui propriedades antioxidantes. Contribui para o conforto articular e muscular, auxiliando no bem-estar das articulações. Auxilia na sensação de alívio em desconfortos na coluna e na musculatura.", img:"imagens/canela_de_velho.png", doencas:["Diabetes","Rins"], preco:"30,00"},
{nome:"Cardo Mariano 30ml", cat:"Extratos", desc:"Extrato fitoterápico.", descLonga:"Tradicionalmente utilizado para auxiliar as funções do fígado e da vesícula. Contribui para a digestão e para o equilíbrio do sistema imunológico. Possui ação antioxidante, ajudando a proteger as células do corpo.", img:"imagens/cardo_mariano.png", doencas:["Fígado"], preco:"30,00"},
{nome:"Carvão Vegetal Ativado 250g", cat:"Cuidados", desc:"Carvão ativado da casca de coco. Auxilia na absorção de odores e impurezas.", descLonga:"Tradicionalmente utilizado para auxiliar na sensação de conforto intestinal e na redução de gases. Contribui para a limpeza da pele e do cabelo, ajudando a remover impurezas. Em situações de emergência, como suspeita de intoxicação ou picadas de animais peçonhentos, procure orientação médica imediata. Este produto não substitui atendimento médico.", img:"imagens/carvao_ativado_em_po.png", doencas:["Intestino","Pele"], preco:"50,00"},
{nome:"Carqueja 30ml", cat:"Extratos", desc:"Extrato fitoterápico.", descLonga:"Tradicionalmente utilizada para auxiliar a digestão e o conforto intestinal. Contribui para o funcionamento do fígado e possui ação diurética. Auxilia na manutenção dos níveis de colesterol já dentro da normalidade.", img:"imagens/carqueja.png", doencas:["Digestão","Diabetes"], preco:"30,00"},
{nome:"Coentro 30ml", cat:"Extratos", desc:"Extrato fitoterápico.", descLonga:"Potente antioxidante natural, contribui para a proteção das células contra os radicais livres e auxilia o sistema imunológico. Ajuda a manter a pele com aspecto hidratado e saudável. Contribui para a digestão e para o equilíbrio da flora intestinal.", img:"imagens/coentro.png", doencas:["Digestão","Colesterol"], preco:"30,00"},
{nome:"Dente de Leão 30ml", cat:"Extratos", desc:"Extrato fitoterápico de Taraxacum officinale.", descLonga:"Tradicionalmente utilizado para auxiliar o funcionamento do fígado e a digestão. Contribui para a manutenção dos níveis de colesterol já dentro da normalidade e para o equilíbrio do organismo.", img:"imagens/dente_e_leao.png", doencas:["Fígado","Rins"], preco:"30,00"},
{nome:"Desodorante Ginger & Tea Tree 70g", cat:"Cuidados", desc:"Desodorante natural.\nCom ação antibacteriana, não mancha, 100% vegano, sem alumínio.", descLonga:"Ingredientes: Água destilada, óleo de gengibre, hidróxido de magnésio, goma xantana e óleo essencial de tea tree.", img:"imagens/desodorante_ginger.png", doencas:["Cuidados Pessoais"], preco:"30,00"},
{nome:"Desodorante Mint & Grape 70g", cat:"Cuidados", desc:"Desodorante natural com aroma de hortelã e uva. 100% vegano, sem alumínio.", descLonga:"Ingredientes: Água destilada, óleo de semente de uva, hidróxido de magnésio, goma xantana, óleo essencial de menta piperita e óleo essencial de agulha de pinheiro.", img:"imagens/desodorante_mint.png", doencas:["Cuidados Pessoais"], preco:"30,00"},
{nome:"Equinácea 30ml", cat:"Extratos", desc:"Extrato fitoterápico.", descLonga:"Tradicionalmente utilizada para auxiliar o sistema imunológico. Contribui para o bem-estar em períodos de maior necessidade de defesas do organismo e possui propriedades anti-inflamatórias.", img:"imagens/equinacea.png", doencas:["Imunidade"], preco:"30,00"},
{nome:"Erva Baleeira 30ml", cat:"Extratos", desc:"Extrato fitoterápico.", descLonga:"Tradicionalmente utilizada para auxiliar no conforto muscular e das articulações. Contribui para o bem-estar da pele e para o funcionamento do sistema imunológico. Pode contribuir para o processo de emagrecimento quando associada a hábitos saudáveis.", img:"imagens/erva_baleeira.png", doencas:["Anti-inflamatório","Dores"], preco:"30,00"},
{nome:"Erva Botão 30ml", cat:"Extratos", desc:"Extrato fitoterápico.", descLonga:"Contribui para a saúde óssea e para o equilíbrio do sistema imunológico. Auxilia na manutenção dos níveis de colesterol e glicose já dentro da normalidade. Pode contribuir para a saúde capilar.", img:"imagens/erva_botao.png", doencas:["Estômago","Digestão"], preco:"30,00"},
{nome:"Espinheira Santa 30ml", cat:"Extratos", desc:"Extrato fitoterápico.", descLonga:"Tradicionalmente utilizada para auxiliar o funcionamento intestinal e o conforto digestivo. Contribui para o bem-estar do fígado.", img:"imagens/espinheira_santa.png", doencas:["Estômago","Gastrite"], preco:"30,00"},
{nome:"Espinheiro Branco 30ml", cat:"Extratos", desc:"Extrato fitoterápico.", descLonga:"Tradicionalmente utilizado para contribuir com a saúde cardiovascular e a circulação sanguínea. Auxilia no relaxamento e pode contribuir para uma rotina de sono mais tranquila.", img:"imagens/espinheiro_branco.png", doencas:["Coração","Pressão"], preco:"30,00"},
{nome:"Folha de Amora 30ml", cat:"Extratos", desc:"Extrato fitoterápico.", descLonga:"Tradicionalmente utilizada para auxiliar o conforto respiratório. Contribui para o bem-estar durante a menopausa e pode auxiliar no processo de emagrecimento quando associada a hábitos saudáveis.", img:"imagens/folha_de_amora.png", doencas:["Diabetes","Feminino"], preco:"30,00"},
{nome:"Folha de Graviola 30ml", cat:"Extratos", desc:"Extrato fitoterápico.", descLonga:"Antioxidante natural, tradicionalmente utilizada para auxiliar no conforto do ciclo menstrual. Possui ação diurética e contribui para o bem-estar geral do organismo.", img:"imagens/folha_de_graviola.png", doencas:["Imunidade","Relaxamento"], preco:"30,00"},
{nome:"Folha de Oliveira 30ml", cat:"Extratos", desc:"Extrato fitoterápico de Olea europaea.", descLonga:"Contribui para o funcionamento do sistema imunológico. Auxilia na manutenção dos níveis de colesterol já dentro da normalidade e contribui para o bem-estar cardiovascular. Possui ação diurética e pode contribuir para a saúde de cabelo e unhas.", img:"imagens/folha_de_oliveira.png", doencas:["Pressão","Coração"], preco:"30,00"},
{nome:"Garra D 30ml", cat:"Extratos", desc:"Extrato fitoterápico.", descLonga:"Tradicionalmente utilizada para auxiliar no conforto articular, com propriedades anti-inflamatórias. Contribui para a digestão e para o bem-estar do fígado. Auxilia na manutenção dos níveis de colesterol já dentro da normalidade.", img:"imagens/garra_D.png", doencas:["Anti-inflamatório","Dores"], preco:"30,00"},
{nome:"Ginkgo Biloba 30ml", cat:"Extratos", desc:"Extrato fitoterápico.", descLonga:"Contribui para a concentração e a memória. Auxilia na circulação sanguínea e pode contribuir para o conforto em situações de tontura relacionadas à circulação.", img:"imagens/ginko_biloba.png", doencas:["Memória","Circulação"], preco:"30,00"},
{nome:"Ginseng 30ml", cat:"Extratos", desc:"Extrato fitoterápico.", descLonga:"Tradicionalmente utilizado como tônico energético, auxiliando no conforto da fadiga física e mental. Contribui para o sistema imunológico e para o equilíbrio em momentos de estresse.", img:"imagens/ginseng.png", doencas:["Energia","Disposição"], preco:"30,00"},
{nome:"Guaçatonga 30ml", cat:"Extratos", desc:"Extrato fitoterápico.", descLonga:"Tradicionalmente utilizada para auxiliar o conforto digestivo, com ação anti-inflamatória. Contribui para a saúde da pele e para a circulação sanguínea.", img:"imagens/guacatonga.png", doencas:["Estômago","Digestão"], preco:"30,00"},
{nome:"Hibisco 30ml", cat:"Extratos", desc:"Extrato fitoterápico.", descLonga:"Possui ação diurética. Contribui para a manutenção da pressão arterial e dos níveis de glicose já dentro da normalidade. Pode contribuir para o processo de emagrecimento quando associado a hábitos saudáveis.", img:"imagens/hibisco.png", doencas:["Pressão","Colesterol"], preco:"30,00"},
{nome:"Hiperico 30ml", cat:"Extratos", desc:"Extrato fitoterápico de Hypericum perforatum.", descLonga:"Tradicionalmente utilizado para auxiliar no equilíbrio emocional e no conforto em momentos de ansiedade. Contribui para uma rotina de sono mais tranquila e para o bem-estar durante a menopausa.", img:"imagens/hiperico.png", doencas:["Humor","Ansiedade"], preco:"30,00"},
{nome:"Inhame Selvagem Feminino 70g", cat:"Cuidados", desc:"Creme de inhame selvagem. Vegano, sem parabenos e aditivos.", descLonga:"Ingredientes: extrato de Dioscorea villosa (Inhame Selvagem Mexicano), extrato de Vitex agnus-castus, óleo de semente de uva, cera vegana, óleo essencial de lavanda, goma xantana. Tradicionalmente utilizado para auxiliar no conforto durante a menopausa e o ciclo menstrual. Modo de uso: aplicar uma pequena quantidade (1 pump) do creme na região desejada.", img:"imagens/inhame_feminino.png", doencas:["Feminino","Hormônios"], preco:"150,00"},
{nome:"Inhame Selvagem Masculino 50g", cat:"Cuidados", desc:"Creme de inhame selvagem. Vegano, sem parabenos e aditivos.", descLonga:"Creme vegano, sem parabenos e aditivos, tradicionalmente utilizado para auxiliar o equilíbrio hormonal masculino. Modo de uso: aplicar uma pequena quantidade (1 pump) do creme na região desejada.", img:"imagens/inhame_masculino.png", doencas:["Masculino","Hormônios"], preco:"150,00"},
{nome:"Ipê Roxo 30ml", cat:"Extratos", desc:"Extrato fitoterápico.", descLonga:"Contribui para o sistema imunológico, com propriedades anti-inflamatórias e antioxidantes. Possui ação diurética e contribui para o bem-estar geral do organismo.", img:"imagens/ipe_roxo.png", doencas:["Imunidade","Pele"], preco:"30,00"},
{nome:"Melão de São Caetano 30ml", cat:"Extratos", desc:"Extrato fitoterápico.", descLonga:"Contribui para a manutenção da pressão arterial e dos níveis de glicose já dentro da normalidade. Possui propriedades anti-inflamatórias e contribui para o bem-estar da pele.", img:"imagens/melao_de_sao_caetano.png", doencas:["Diabetes","Pele"], preco:"30,00"},
{nome:"Mentrasto 30ml", cat:"Extratos", desc:"Extrato fitoterápico.", descLonga:"Tradicionalmente utilizado para auxiliar no conforto do ciclo menstrual e no bem-estar geral do organismo.", img:"imagens/mentrasto.png", doencas:["Digestão","Intestino"], preco:"30,00"},
{nome:"Mulungu 30ml", cat:"Extratos", desc:"Extrato fitoterápico.", descLonga:"Tradicionalmente utilizado por sua ação calmante. Contribui para o relaxamento e para uma rotina de sono mais tranquila, auxiliando no conforto em momentos de agitação.", img:"imagens/mulungu.png", doencas:["Sono","Ansiedade"], preco:"30,00"},
{nome:"Óleo de Alho 60ml", cat:"Óleos Vegetais", desc:"Óleo vegetal de alho.", descLonga:"Tradicionalmente utilizado para contribuir com o bem-estar geral do organismo. Possui propriedades antioxidantes, auxiliando a reduzir os efeitos dos radicais livres. Pode contribuir para a saúde cardiovascular e para o equilíbrio do sistema imunológico.", img:"imagens/oleo_de_alho.png", doencas:["Imunidade","Circulação"], preco:"50,00"},
{nome:"Óleo de Argan 60ml", cat:"Óleos Vegetais", desc:"Óleo vegetal de argan.", descLonga:"Rico em vitamina E e ácidos graxos. Contribui para a hidratação e nutrição da pele e dos cabelos, auxiliando no combate aos radicais livres e na sensação de maciez.", img:"imagens/oleo_de_argan.png", doencas:["Pele","Cabelos"], preco:"50,00"},
{nome:"Óleo de Linhaça Dourada 60ml", cat:"Óleos Vegetais", desc:"Óleo vegetal de linhaça dourada.", descLonga:"Rico em ômega-3. Contribui para a manutenção dos níveis de colesterol já dentro da normalidade e auxilia o funcionamento do sistema digestivo.", img:"imagens/oleo_de_linhaca_dourada.png", doencas:["Digestão","Colesterol"], preco:"50,00"},
{nome:"Óleo de Massagem 140ml", cat:"Óleos Vegetais", desc:"Óleo de massagem corporal.", descLonga:"Formulado para proporcionar relaxamento e cuidado com a pele. Contribui para a hidratação e para a sensação de bem-estar durante a massagem.", img:"imagens/oelo_de_massagem_140_ml.png", doencas:["Relaxamento","Cuidados Pessoais"], preco:"70,00"},
{nome:"Óleo de Massagem 1 Litro", cat:"Óleos Vegetais", desc:"Óleo de massagem corporal (1 litro).", descLonga:"Composição: Óleo de semente de uva, óleo de amêndoas, óleo de camomila, óleo de calêndula, óleo essencial de menta piperita, óleo essencial de lavanda e óleo essencial de eucalipto. Contribui para o relaxamento muscular e para uma sensação de bem-estar. Auxilia na hidratação e elasticidade da pele.", img:"imagens/oleo_de_massagem_1_L.png", doencas:["Relaxamento","Cuidados Pessoais"], preco:"200,00"},
{nome:"Óleo de Orégano 60ml", cat:"Óleos Vegetais", desc:"Óleo vegetal de orégano.", descLonga:"Possui propriedades antioxidantes. Contribui para a manutenção dos níveis de colesterol e glicose já dentro da normalidade e auxilia a digestão. Pode contribuir para o processo de emagrecimento quando associado a hábitos saudáveis.", img:"imagens/oleo_de_oregano.png", doencas:["Imunidade","Respiratório"], preco:"50,00"},
{nome:"Óleo de Rícino 60ml", cat:"Óleos Vegetais", desc:"Óleo vegetal de rícino.", descLonga:"Tradicionalmente utilizado para uso tópico no cuidado da pele e dos cabelos. Contribui para a sensação de hidratação e pode auxiliar no aspecto saudável do couro cabeludo.", img:"imagens/oleo_de_ricino.png", doencas:["Cabelos","Pele"], preco:"50,00"},
{nome:"Óleo de Rosa Mosqueta 60ml", cat:"Óleos Vegetais", desc:"Óleo vegetal de rosa mosqueta.", descLonga:"Óleo de rosa mosqueta puro. Contribui para a hidratação profunda da pele e auxilia na sensação de uniformidade e viço, sendo tradicionalmente utilizado no cuidado de marcas na pele.", img:"imagens/oleo_de_rosa_mosqueta.png", doencas:["Pele"], preco:"50,00"},
{nome:"Óleo de Semente de Abóbora 60ml", cat:"Óleos Vegetais", desc:"Óleo vegetal de semente de abóbora.", descLonga:"Rico em ácidos graxos essenciais. Contribui para a nutrição e elasticidade da pele e pode auxiliar no equilíbrio hormonal. Fortalece cabelo e unhas.", img:"imagens/oleo_de_semente_de_abobora.png", doencas:["Masculino","Circulação"], preco:"50,00"},
{nome:"Óleo de Semente de Uva 60ml", cat:"Óleos Vegetais", desc:"Óleo vegetal de semente de uva.", descLonga:"Rico em antioxidantes e ácidos graxos essenciais. Hidrata e nutre a pele, auxilia contra os radicais livres e contribui para a circulação.", img:"imagens/oleo_de_semente_de_uva.png", doencas:["Pele","Colesterol"], preco:"50,00"},
{nome:"Óleo Essencial de Alecrim 30ml", cat:"Óleos Essenciais", desc:"Óleo essencial 100% puro.", descLonga:"Tradicionalmente utilizado para auxiliar a concentração e a memória. Possui propriedades antioxidantes e contribui para a saúde capilar.", img:"imagens/oleo_essencial_de_alecrim.png", doencas:["Memória","Digestão"], preco:"50,00"},
{nome:"Óleo Essencial de Copaíba 30ml", cat:"Óleos Essenciais", desc:"Óleo essencial 100% puro.", descLonga:"Ingredientes: 100% Óleo Essencial de Copaifera Officinalis. Pode ser usado em aplicações de aromaterapia e em massagens.", img:"imagens/oleo_essencial_de_copaiba.png", doencas:["Anti-inflamatório","Pele"], preco:"45,00"},
{nome:"Óleo Essencial de Eucalipto 30ml", cat:"Óleos Essenciais", desc:"Óleo essencial 100% puro.", descLonga:"Óleo Essencial de Eucalipto Globulus 100% puro. Tradicionalmente utilizado para auxiliar o conforto respiratório e para purificar o ambiente.", img:"imagens/oleo_essencial_de_eucalipto.png", doencas:["Respiratório"], preco:"40,00"},
{nome:"Óleo Essencial de Hortelã Pimenta 30ml", cat:"Óleos Essenciais", desc:"Óleo essencial de Mentha piperita, 100% puro.", descLonga:"Refrescante e estimulante, contribui para o conforto digestivo e para a concentração.", img:"imagens/oleo_essencial_de_hortela.png", doencas:["Digestão","Respiratório"], preco:"50,00"},
{nome:"Óleo Essencial de Lavanda 30ml", cat:"Óleos Essenciais", desc:"Óleo essencial 100% puro.", descLonga:"Calmante e relaxante, contribui para o bem-estar em momentos de ansiedade e para uma rotina de sono mais tranquila. Auxilia no cuidado da pele.", img:"imagens/oleo_essencial_de_lavanda.png", doencas:["Sono","Relaxamento"], preco:"60,00"},
{nome:"Óleo Essencial de Limão Siciliano 30ml", cat:"Óleos Essenciais", desc:"Óleo essencial 100% puro.", descLonga:"Antioxidante e energizante, contribui para a purificação do ambiente e auxilia na digestão.", img:"imagens/oleo_essencial_de_limao_siciliano.png", doencas:["Imunidade","Digestão"], preco:"45,00"},
{nome:"Óleo Essencial de Melaleuca 30ml", cat:"Óleos Essenciais", desc:"Óleo essencial 100% puro.", descLonga:"Tradicionalmente utilizado no cuidado da pele e em aromaterapia, contribuindo para o bem-estar e o sistema imunológico.", img:"imagens/oleo_essencial_de_melaleuca.png", doencas:["Pele","Imunidade"], preco:"50,00"},
{nome:"Própolis Verde 70% 30ml", cat:"Extratos", desc:"Extrato de própolis verde, não alcoólico.", descLonga:"Ingredientes: Água destilada e própolis verde em natura. Contribui para o sistema imunológico e possui propriedades anti-inflamatórias.", img:"imagens/propolis_verde.png", doencas:["Imunidade","Garganta"], preco:"36,00"},
{nome:"Regeneração Hepática 60ml", cat:"Extratos", desc:"Composto com Alcachofra, Dente de Leão e Espinheira Santa.", descLonga:"Ingredientes: Água destilada, Alcachofra, Dente de Leão, Espinheira Santa e Glicerina Natural. Auxilia a função digestiva e contribui para a sensação de corpo mais leve. Pode contribuir para o processo de emagrecimento quando associado a hábitos saudáveis, auxiliando na redução do inchaço e da retenção de líquidos.", img:"imagens/propolis_verde.png", doencas:["Fígado","Digestão"], preco:"60,00"},
{nome:"Quitoco 30ml", cat:"Extratos", desc:"Extrato fitoterápico.", descLonga:"Tradicionalmente utilizado para auxiliar no equilíbrio do ciclo menstrual e no bem-estar do sistema reprodutor feminino.", img:"imagens/quitoco.png", doencas:["Estômago","Digestão"], preco:"30,00"},
{nome:"Salsaparrilha 30ml", cat:"Extratos", desc:"Extrato fitoterápico.", descLonga:"Possui propriedades anti-inflamatórias, contribuindo para o conforto articular. Auxilia a circulação sanguínea.", img:"imagens/salsa_parrilha.png", doencas:["Pele","Rins"], preco:"30,00"},
{nome:"Sérum Facial Regenerador 30ml", cat:"Cuidados", desc:"Sérum facial regenerador.", descLonga:"Sérum facial com ingredientes naturais. Contribui para a hidratação e nutrição da pele, auxiliando no viço e na sensação de pele saudável.", img:"imagens/serum_facial.png", doencas:["Pele"], preco:"35,00"},
{nome:"Sucupira 30ml", cat:"Extratos", desc:"Extrato fitoterápico.", descLonga:"Contribui para o conforto articular, com propriedades anti-inflamatórias. Auxilia na sensação de alívio de dores musculares. Tônico tradicionalmente utilizado para o bem-estar geral do organismo.", img:"imagens/sucupira.png", doencas:["Anti-inflamatório","Dores"], preco:"30,00"},
{nome:"Tansagem 30ml", cat:"Extratos", desc:"Extrato fitoterápico.", descLonga:"Tradicionalmente utilizada por suas propriedades anti-inflamatórias, contribuindo para o conforto respiratório e para o cuidado da pele.", img:"imagens/tansagem.png", doencas:["Respiratório","Intestino"], preco:"30,00"},
{nome:"Tribulus Terrestre e Maca Peruana 30ml", cat:"Extratos", desc:"Extrato fitoterápico combinado.", descLonga:"Composto de Tribulus Terrestre e Maca Peruana, tradicionalmente utilizado para contribuir com a energia e a disposição física. Auxilia no bem-estar geral e na sensação de vigor no dia a dia.", img:"imagens/tribulus_e_maca.png", doencas:["Energia","Masculino"], preco:"30,00"},
{nome:"Unha de Gato 30ml", cat:"Extratos", desc:"Extrato fitoterápico de Uncaria tomentosa.", descLonga:"Contribui para a circulação sanguínea e para o funcionamento do sistema imunológico.", img:"imagens/unha_de_gato.png", doencas:["Imunidade","Anti-inflamatório"], preco:"30,00"},
{nome:"Uxi Amarelo 30ml", cat:"Extratos", desc:"Extrato fitoterápico.", descLonga:"Tradicionalmente utilizado para auxiliar no bem-estar do sistema reprodutor feminino e no conforto digestivo.", img:"imagens/uxi_amarelo.png", doencas:["Feminino","Intestino"], preco:"30,00"},
{nome:"Valeriana 30ml", cat:"Extratos", desc:"Extrato fitoterápico de Valeriana officinalis.", descLonga:"Tradicionalmente utilizada para contribuir com uma rotina de sono mais tranquila e para o conforto em momentos de ansiedade. Auxilia no bem-estar durante a menopausa.", img:"imagens/valeriana.png", doencas:["Sono","Ansiedade"], preco:"30,00"},
{nome:"Vitex 30ml", cat:"Extratos", desc:"Extrato fitoterápico de Vitex agnus-castus.", descLonga:"Contribui para o conforto durante a menopausa e a tensão pré-menstrual. Auxilia no equilíbrio hormonal feminino.", img:"imagens/vitex.png", doencas:["Feminino","Hormônios"], preco:"35,00"}
];
